namespace AdventOfCode.Puzzles.Day12;

using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using NUnit.Framework;

[MemoryDiagnoser(false)]
[SimpleJob(RuntimeMoniker.Net90, baseline: true, iterationCount: 20)]
public class Puzzle2
{
    [Test]
    [Benchmark]
    public void Solve()
    {
        var grid = PuzzleInput
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(x => x.ToCharArray())
            .ToArray();
        var rows = grid.Length;
        var cols = grid[0].Length;

        var visited = new bool[rows, cols];
        var directions = new[] { (-1, 0, "up"), (0, 1, "right"), (0, -1, "left"), (1, 0, "down") };
        var result = 0;

        var queue = new Queue<(int x, int y)>();
        var edges = new HashSet<(int x, int y, string direction)>();
        var processedEdges = new HashSet<(int x, int y, string direction)>();

        for (var i = 0; i < rows; i++)
        {
            for (var j = 0; j < cols; j++)
            {
                if (!visited[i, j])
                {
                    edges.Clear();
                    processedEdges.Clear();

                    queue.Enqueue((i, j));
                    visited[i, j] = true;

                    var area = 0;
                    var type = grid[i][j];

                    while (queue.Count > 0)
                    {
                        var (x, y) = queue.Dequeue();
                        area++;

                        foreach (var (dx, dy, direction) in directions)
                        {
                            var nx = x + dx;
                            var ny = y + dy;

                            if (nx >= 0 && nx < rows && ny >= 0 && ny < cols)
                            {
                                if (grid[nx][ny] != type)
                                {
                                    edges.Add((x, y, direction));
                                }
                                else if (visited[nx, ny] is false)
                                {
                                    visited[nx, ny] = true;
                                    queue.Enqueue((nx, ny));
                                }
                            }
                            else
                            {
                                edges.Add((x, y, direction));
                            }
                        }
                    }

                    var uniqueEdges = edges.Count;

                    foreach (var e1 in edges)
                    {
                        processedEdges.Add(e1);

                        foreach (var e2 in edges)
                        {
                            if (processedEdges.Contains(e2) || e1.direction != e2.direction)
                            {
                                continue;
                            }

                            var dx = Math.Abs(e2.x - e1.x);
                            var dy = Math.Abs(e2.y - e1.y);

                            if (dx is 0 && dy is 1 || dx is 1 && dy is 0)
                            {
                                uniqueEdges--;
                            }
                        }
                    }

                    result += area * uniqueEdges;
                }
            }
        }

        Console.WriteLine(result);
    }

    private const string PuzzleInputTestSmall = """
        AAAA
        BBCD
        BBCC
        EEEC
        """;

    private const string PuzzleInputTestE = """
        EEEEE
        EXXXX
        EEEEE
        EXXXX
        EEEEE
        """;

    private const string PuzzleInputTest = """
        AAAAAA
        AAABBA
        AAABBA
        ABBAAA
        ABBAAA
        AAAAAA
        """;

    private const string PuzzleInput = """
        DDDDDDDAAAAAAAAAAAAAAAAIIIIIIIIEEEEEEEERRRRRBBBBBRRRRRRRRRRRRIUUUIXIIIIIPPPPPPPPPPPPPPWWPPPPPPPPXXXXHXXUUUUUUUUUUUUUUUPWWWWWWWWWCJJJJJJZZZZZ
        DDDDDDAAAAAAAAAAAAAAAAAAIIIIIIIIEEEEEERRRRRBBBBBBBBRRRRRRRRRIIUUUIIIIIIIPIPPPPPPPPPPPPPWPPPPPPPXXXXXXXXUUUUUUUUUUUUUUUPWWWWWWWWWJJJJJJJZZZZZ
        DDCCCCCAAAAAAAAAAAAAAAAAAIIIIIIEEEEEEERRRRRBBABBBBBRRIRRRRRRIIIIIIIIIIIIIINNPPPPPPPPPPPWPWWWPPPXXXXXXXXUUUUUUUUUUUUUUUPPPWWWWWWWJJJJJJZZZZZZ
        DDCCCCAAAAAAAAAAAAAAAAAAAIIIIEEEEEEEEERRRRRBBBBBBBBRRIRRRIIIIIIIIIIIIIIIINNPPPPPHPHHPPPWWWWWWWXXXXXXXXVVUUUUUUUUUUUPUPPPPPWWWWWJJJJJJJZZZZZZ
        CCCCCCCAAAAAAAAAAAAAAAAAEIIIIIIIEEEEEERRRRRRBBBBBBBIIIIIIYIIIIIIIIIIIIIIINNNPPPPHHHHPPWWWWWWWYXXXXXXVVVUUUUUUUUUUUUPUPPPPPPWWWWJJJJJJJJZZZZZ
        CCCCCCCATTAAALAAAAAEEAAEEIIIIIIIEEEEEERRRRBBBBBBBBBIIIIIIIGDGIIIIIIIIINNNNNNPPPHHHHHPPWWWWWWXXXXXXXXVVVVVUUVUUUUUUUPPPPPPPPPPWWJJJJJJJJJZJZZ
        CCCCCCCATTAAALAAAAAEEEEEEEIIISIIIEEEEEERRRBBBBBBBBIIIIIIIIGGGGIIIIIINNNNNNNNPPPPHHHHWWWWWWWWWWXXXXVXVVVVVVVVVUUUUUPPPPPPPPPPPWJJJJJJJJJJJJZZ
        ZCCCCTTTTTAANAAAAAAEEEEEEEIIIIIIUEEEERRRRBBBBBBBBBIGIIIIIDGGGGGIIIIINNNNNNNNPPHHHHHHHWWWWWWWWXXXXXVVVVVVVVVVVUUUUPPPPPPPPPPPSJJJJJJJQJJJJJZZ
        CCCCCCCTTTATAAAAMEEEEEEEEUIUIIUUUUEEERRRBBBBBBBBBBDDIIIIIDGGGJGIIIIIINNNNNNNNNNTHHHHHWWWWWWWWWXXXXVVVVVVVVVVUUUUUPPPPPPPPPPPPSSUUJJJQJJJJJZZ
        CCCCCCTTTTTTAAAAEEEEEEEEEUUUUUUUUUUEEEUUUUBBBBBBBBBDIIDDDDGGGGGGIIIIINNNNNNNNNNTHHHHHHWWWWWWBWXVVVVVVVVVVVVVVVUUPPPPPPPPPPPPPSPUUJJJQKJJMJZZ
        CCCCCCCTAAAAAAAAAEEEEEEEUUUUUUUUUUUUUUUUUUBUBBBBDDDDDDDDDDGGGGIIIIISNNNNNNNNNNNNHHHHHWWWWWWBBWCVZZVVVVVVVVVVVVUUPPPPPPPPPPPPPPPUUUUQQQAQQQZZ
        CCCCCCCAAAAAAAAAEEEEEEEGUUUUUUUUUUUUUUUUUUUUUBBBDDDDDDDDDDGGGGGRPPPPPPNNNNNNNHHHHHHHWWWWWWWWWWWZZZZVVVVVVVVVVVVVFPPPPPPPPPPPPPPUUUUBQQQQQQQZ
        KCCCCKAAAAAAAAAAAEEEEEEEEUUUUUUUUUUUUUUUUUUUUBBDDDDDDDDDDDDGGGPRPPPPPNNNNNNNNHHHHHHHHWWWWWWWZZZZZZZVVVVVVVVVVVVVVPPPPBBPPPPPPIIUUUBBQQQQQQQQ
        KKCCCKAAAAAAAAAARRAPENNNPUPUUUUUUUUUUUUUUUUKDDDDDDDDDDDDDDDGPGPPPPPPNNNNNNNNNHHHHHHWWWYWWWWZZZZZZZZZZVVVVVVVVVVVQQBBBBBBPPPPPPIUUUUBBQQQQQQQ
        KKCCKKAYAAAAAAAAAAAPENNNPPPPUUUUUUUUUZZZZZKKKDKDMMDDDDDDDDDDPPPPPPPPPPNNNNNNNNHHHHHHWYYWWWWWWZZZZZNZZVVUVVVVVVQVQQQBBBBPPPPPPPJUBBBBQQQQQQQQ
        KKKKKKAAAAAAAAAAAAAPENNNPPPPPUUJUUUUZZZZZZKZKKKDDDDDDDDDDDDDPPPPPPPPPPIINNNNNHHHHPHHWWWWWWWWWZZZNNNZZZVUUUUUVVQQQJJQQQBBPPPMPJJJJJJQQQQQQQQQ
        KKKKKKAAAAAAAAAAAAPPPNNNPPPPPPPJUUUZZZZZZZZZZKKDDDDDDFDDDDDPPPPPPPPPPPNNNNNNNHPPPPHWWWWWWWWWWZZZNNNNNNVUUUUUUQQQQQQQQQQBBRRRRRJJJJJQQQQQQQQQ
        KKKKKKKKATAAAAAGJPPPJNNNJJPMPPJJJUUUZZZZZZZZZKKDDDDDDFDDDDDDPPPPPPPPPMMMNNNZNNPPPPWWHWWPWWWWNZZZNNNVVNVUUUKKQQQQQGGQQRQRRRRRRRJJJJJJJFQQFFFF
        KKKKKKKKKTTAAAGGJJJJJNNNJJJJJPJJJUUUUZLZZZZZZKKDDDDFFFDDDDDDDVPPPPPPPPPMNNNNCCCCPPPWHPPPWWWWNNNNNNNVVNVVVUKKQQQQQRGRRRRRRRRRRRRERJJJJFFFFFFF
        KKKKKKKKKTTTTTGGGJJJJNNNJJJJJJJJOUUUUUZZZZZZZKKDKKDFFFFFFDDDDPPPEPPXPZPMMMMMMMMCPPPPPPPPWPWWNNNNNNNVVVVVVUKKKQQQRRGRRRRRRRRRRRRRRRJZBFFFFFFF
        KKKKKKKKKTTTTTTGGGJJJNNNJJJJJJJFOOUUUUZZZZZZZKKKKKDPFFFFFFFFEEEEEDDDMMMMMMMMMMMMPPPPPPPPPPPWNNNNIINVVVVVVVKKKKBBBRGRRRRRRRRRRRRRRRRBBBFFFFFF
        KKKKKKKTKTTTTTTTTJJJJNNNJJJJJJJFOOUAUNNZZZFFZKKKHKHPFFFFFFFFEEEEEEDDDDDMMMMMMMMUPPPPPPPPPPPPPNNIIIVVVVVVVBBBKKBBRRRRRRRRRRRRRRRRRRSBBBBBFFFF
        KKKKKKTTKKTTKKKKGJJJJNNNJJJJJJJOOOOAUNNZZFFFFKKKHHHHFFFFFFFFEEEEEDDDDXXXXMMMMMMPPPPPPPPPPPPPQHNIIIVVVVVVVBBBBBBBBRRRRRRRRRRRRRRRRRRBBFFFFFFF
        KKKKKKTTTTTTKKKMMJJJJJJJJJJJJJJJOOOONNNNZNNNHHHHHHXXFFFFFFFEEDEEDNDDDDXXXXMMMMMMPPPPPPPPPPPPQHNIIVVVVVVVVBBBBBBBBBRRRRRRRRRRRRRRRRBBBBBFFFFF
        KKKKKKKTTTKKKKKMMRJJJJJJJJJJJJJJOOOOONNNNNNHHHHHHHXXFIFFFFFFDDDDDDDDDDXXXXXXMHHHPPPPHHPPPPPQQHHIIVVVVVVVVBBBBBBBBBRRFFRRRRRRRRRRRBBBBBBBFFFF
        KKKKKKKKMTKKKKKMMMJMMMMJJJJJJJJOOOOOONNNNNNHHHHHHHHHFFFFFFDRDDDDDDDDDXXXXXXXMHHHPPPPHHPPPPPPHHHIIVZZZZZBBBBBBBBBBBRKFFFFRRRRRRRBRRRBBBBBBFFF
        KKKKEEKMMOKKKJMMMMMMMMMJJSJJJJJOOOOOOONNNNGHHHHHHHHIFFFFFDDDDDDDDDDDDXXXXXXXXXHHHHPHHHHPPPPPHHZIIZZZZBBBBBBBBBBBFFKKFFFRRRFRFFFBBRRBBBBBBBBF
        KKKKKOOOMOKKKOMMMMMMMMMMMSJJJJJOOOOOOONNNNGHHHHHHHHHFFFFDDDDDDDDDDDDDDDDXXXXXXHHHHHHHHHPPPHHHHZIIZZBBBBBBBBBBBBBFFFFFFFFFFFFFFBBBBBBBBBBBBBB
        KKKKKOOOOOKKOOFMMMMMMMMMMMJJJJOOOOOOOONNNNGHHHHHHIHLFFFFFDZDDDDDDDDDDDDXXXXXXXXHHHHHHHHHPPHHHOZIZZZZZBBBBBBBBBBBFFFFFFFFFFFFFBBBBBBBBBBBBBBB
        KKKKOOOOOOOOOOMDMMMMMMMMMMFFJOOOOOOZZZNZNZGHHHHHHHHLFFFFFDDDDDDDDDDDDDDXXXXXXXXXXXXHHHHPPPHHHZZZZZZZZBBZZWWBBWWFFFFFFFFFFFFFFBBBBBBBBBEEEBBB
        KEOOOOOOOOOOOOMMMMMMMMHMMMIFFFOOOOOOZZZZZZGHHHHHHHHFFFFFFFDDDDDDDDDDDXXXXXXXXXXXHXXHHHHHHHHHHZZZZZZZZZBZZQWWWWWFFFFFFFFFFFFFFFBFBBBBBVEEBBBE
        EEOOOOOOOOOOOOMMMMMMMMHHIIIBFOOOOOOOZZZZZZGGGHBVYHHFFFFFFFPPDDDDDDDNNNXXXXXXXXXXHXHHHHHHHHHHHWZZZZZZZBBZZWWWYWWFFIFFFFFFFFFFFFFFDDBBBBBEEEEE
        EEOOOOOOOOOOOOXMMGMMZMMHIIZUUUOUUUOUUZZZZZGCVVVVVVHFFFFFFPPPDDDDDDNNNNXXXXNCXXXXHXHHHHHHHHHHHZZZZZZZZZZZZZWWWWWFFFFFFFFFFFFFFFFFDDDBBBBEEEEE
        EEEOOOOOOOOOOOOGGGMGMMHHHUUUUUUUUUUUUUZUZUCCCCVVVVEEAAFFFPPPZDDDDNNNNNNXNXNCCXCVHHHHHHHHHHHHZZZZZZZZZZZZZZWWWWWFWFFFFFFFFFFFFFFFDDDBBBBEEEEE
        EEEOOOOOOOOOOOOGGGGGMMHUUUUUUUUUUUUUUUUUUUUUCVVVVEEEEAAFPPPPZDDDNNNHNNNNNNNNCCCVCCCCHHHHHHHHZZZZZZZZZZZZZWWWWWWWWWWWFFFFZZIIIFZIIIIBEEEEEEEE
        EEEEOOOOOOOOXXGGGGGGGMMUUUUUUUUUUUUUUUUUUUUUCVVVCEEPPAAAPPPPZDDNNNNHNNNNNCCCCCCCCCCCCHHHHHHHZZZZZZZZZZZZZLWWWWWWWWWWFFFFIIIIIFFIIIOEEEEEEBEE
        EEEEEEOOOOOOXXGGGGGGGGGGGUUUUUUUUUUUUUUUUUUCCVVVEEEPPPPPPPPPPJDDNNHHNHNNCCCCCCCCCCCCCHHHHHHZZZZZZZZZZZZZZZWWWWWWWWWWFFTFTIIIIIIIIIIIEEEBEBEE
        EEEEEYYYOYYOXXXGGGGGGGGGGUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJJJIIHHHHNCJCCCCCCCCCCCCCCHHHHIIIIZZZTTZZDDZVJJJWWWWWWFFTTTTTIIIIIIIIIEEEBBBBBB
        EEEREEYYYYYXXXTGGGGGGGGGKUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJIIISSHHCCCCCCCCCCCCCCCCCCCAHHHIIIIZZTTTTJJJJJJJWWWWWWFWWWIIIIIIIIIIIIIEEBBBBBB
        HEEEEEYYYYXXTTTGGGGGGGGKKKKGUUUUUUUUAUUUCCCCCCCCCCCPPPPPPPPPJJIIISHHHHHHHCCCCCCCCCCCCCCCAAHHHIIIZEITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIIIWBBBBBBB
        HHHHHYYYYXXXXTTTGTGGGGKKKKKUUUUUUUULAAAAAWWWWWWWCCPPPPPPPPPPJJJIITHHHHHHCCCCCCCCCCCCCCCAAAAIIIIIIIITTTTTJJJJJJJWWWWWWWIIIIIIIIIIIIIIBBBBBBBB
        HHHHYYYYYYXXXTTTGTGGGGKKKKKKLLUUAUULAAAAAWWWWWWWWWWWPPPPPPPPPPTTTTHHHHHHCCCCCCCCCCCCCAAAAAAAIIIIIIIITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIICCBBBBBB
        HHHHHYYYYYYTTTTTTTTTTGGKKKKLLLULAAAAAAAABWWWWWWWWWWWPPPPWWPTPTTTTTTHHHHHCCCCCCCCCCCCCCAAAAAIIIIIIIIITTTTJJJJJJJWWWWWWVVIIIIIIIIIIIIIIIBBBBBB
        HHHHHHHHYYYUTTTTTTTTTTTTTCKKLLLLAAAAAAAABWWWWWWWWWWWPPWWWWWTPTTTTTTHHHHHHTCCCCCCCCCCCAAAAAIIIIIIIIIITTTJJJJJJJJWWWWWVVVIIIIIIIIIIIIIIBBBBBBB
        HHHHHHHHYYYUUTTTTTTTTTTUUKKKLLLAAAAAAAAAAWWWWWWWPPPPFFWWWWWTTTTTTTTHHHHHHTTTTTCCCCCAAAAAAAAAIIIIIIIIITTTJJJJJJJPWWWVVVVVVVIIIIIIIBBIBBBBBBBB
        HHHHIHIHYHHUUTTTTTTTTTTTTEKLLLLLAAAAAAAPJWWWWWWWPPPPFFWWWWWTTTTTTTTTTHHHHTTTTTCCCCJAAAAAAAAAIIIIIIIIIITTTJJPJJJPPWWVVVVVVVVIIIIIBBBBBBBBBBBB
        HHIIIIIHUUUUUUTTTTTTTTTTEEKWWLLLACAGAAAPPWWWWWWWPPPFFFFWWTTTTTTTTTTTTHHHTTTTTTTTTQJAAAAAAAAAIIIIIIIIIITCTTJPPPPPPPPVPVVVVVVTTTIIBBBBBBBBBBBB
        IIIIIIZUUUUUUTTTTTTTTTTTTTPWWWPPPPBAAPPPPWWWWWWWPPPFFFFFFLLLLTTTTVTTTTTTTTTTTTTTTQQLAAQQAAQIIIIIIIIICCCCTPPPPPPPPPPPPVVVEVEETTIIBBBBBBBBBBBB
        IIIIIIZUUUUUTTTTTTTTTTTTTDWWWWWPPPBBPPPPPWWWWWWWPFFFFFFLLLLLLLEVETTTTTTTTTTTTTTTTTQQWQQQQQQLIIIIYIIPPPCCCCPPPPPPPPPPEVVVEVEETTIIPBBBBBBBBBBB
        IIIIIIIIUUUUUUTTTTTTTTTTTWWWWWPPPBBBPPPPPPPPPPPPPPFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQIIIIYNIPPPPPCCCPPPBPPPPPEEEEEEETTTITPBBBBBBBBBBB
        IIIIIIKKUUUUUUTUUTTTGTGGGWWQWWPPPBBBPPPPPPPPMMPMPFFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQQQQYYNNNNPPCCCCCPPBPPPPPEEEEEEETTTTTBBBBBBBBBBBB
        IIIIIIIIUUUUUUUUTTTTGGGGGWJWWPPPPBBBBPPPPPMMMMMMMFFFFFLLLLLLLLEEEEEEEEEAATTTTTQTTQQQQQQQQQQQQQQQYNNNPPPCCCCCCCBBPPPEEEEEEEEETTTTBBBBBBBBBBJJ
        IIIIIIIIUUUUUUUUTTTTGGGGGWWGPPPPPPPBBPBPEPJMMMMMFFFFFFFLLLLLLLLEEEEAAEAAATAAQQQQQQQQQQQQQQQQQQHHYNNNPPPCCCCCCCCBPPPEEEEEEEEEETTTTBBHBBHHBBBB
        IIIIIIIUUUUUUUUUTTTGGGGGGGGGGPPPPPPBBBBMMJJMMMMPPFFFFFFFLLLLLLEEEEAAAAAAAAAAAQRQQQQQQQQQQQQQQHHHHJNPPPPPGGCCCCCPPPEEEEEETTTEETTTTHHHBHHBBBBB
        IIIIIIUUUUUUUUUUUUWWGGGGGGGGGPPPPPPPMBMMMMMMMMMMMFFFFFFLLLLLLLEAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPPJGGCCCCGGGEEEEETTTTTTTTTTTHHRHHHBBBB
        MIIIIIUUUUUUUUUUUUWWWGGGGQQGGGPPPPPPMMMMMMMMMMJJJFFFFFLLLLLLALAAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPGGGGCGGGGGGEGGEETTTTTTTTTTHHHHHHHHBBB
        IIIIIOUUUUUUUUUUUWWWWWQQQQQGPPPPPLPMMMMMMMMMMMMJJJFFXXLLLLAAAAAAAAAAAAAAAAOOOOOZZZZQQBBBBBBBWWHHHPPPPPPGGGGGGGGGGGGGTTTTTTTTHTHHHHHHHHHHBBBB
        IIIILUUUUUUUUUUUWWWWWGQQQQQQQQPPPLPMMMMMMMMMMMMJJJJFXXXXLLLLAAAAAAAAAAAAAAOOOOOYBBBBBBBBBBBBWWWHHPPPPPGGGGGGGGGGGSSSTTTTTTTTHHHHHHHHHHHHHBBB
        SIIILLUUUUUUUUUWWWWWWGQQQQQQQQQPQMMMMMMMMMMMMMMJJJJFXXXXXLAAAAAAAAAAOOOOOOOOOOOYBBBBBBBBBBBBWZHHHPPPPPGGGGGGGGGGSSSSSTTTTQQQHHHHHHHHHHHHHHHH
        SIIILLUUUUUUUUUWWWWWGGQQQQQQQQQQQMMMMMMMMVVVVMJJJJJXXXXXXXYAAAAOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZZPPPPPPGGGGGGGGGGGSSSTTTTTTQQQHGGHHHHHHHHHHHH
        CCCCCCCUVVUUUUWWWWWQQQQQQQQQQQQQQQMMMMMMVVVZVVJJJJXXXXXXXXAAAAAOOOOOOOOOOOOOOYYZBBBBZBBBBBBBZZZPPPPPPGGGGGGGGGGGSSGRTTTTQQQQQGGGHHHHHHHHHHHH
        CCCCCCCCCCPKUUWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVJXXXXXXXXXNNAALOOOOOOOOOOOOOOYYYBBBBZBBBBBBBJZZOPPPPPPPGGGGGGGGGGGGGTTTTTTQQQQMMSSHHHHHHHHHH
        SSCCCCCCCCKKWWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVXXXXXXXXXBBNNDALOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZOPPPPPPUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKHKKKKKKK
        SCCCCCCCCKKWWWWWWWWQQQQQQQQQQQQQQQMMMMMVVVVVVVVQXXXXXXXXXBNNDAAOOOOOOOOOOOOOOYNNBBBBBBBBBBBBZOOOPPPPPUUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKKKKKKKKK
        SCCCCCCCUKFWWWWWWWWWQQQQQQQQQQQQQEEMMMMVVVVVVVVVXXXXXXXXXXNNNAAOOOOOOXXXXXXXXYYNBBBBBBBBBBBZZOEEEEPPPUUUUGGGGGGGGGGGGGUUTZZZZMMMSMMMJJKKKKKK
        SSSCCCCCUGGGGWWWWWWWQQTQQQQQQEQQQEEMMMMMVVVVVVEEEXXXXXXXXNNNNNGOOOXXXXXXXXXXXQXNBBBBBBBBBBBZUUBEEEUUUUUUUUKGGGGGGTGGGGUUTZZZMMMMMMMMJJKKKKKK
        CCCICCCCGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMMVVVVVVEEEGXXXXXNXXNNIDGOOOXXXXXXXXXXXQQNBBBBBBBBBBBZUUUUUEUUUUUUUUUGGUGCCTTGUUUUUZZZPMMMMMMMJJKKKKKK
        CCCCCCCGGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMVVEVEVVEGEGGXRXNNDDDDDDGOOOXXXXXQQQQQQQQNNNBBBBBBBBBBBBUUUUUUUUUUUUUNCCCCCTCCCUUUUUUUUUUUUUUMMKKKKKKK
        HCCCCCCGGGGGGGGGWWWWWWWQQQQQQEEEEEEETTTTVEEEEEEGGGGXXMDDDDDDDDDGXXXXXXXXXQQQQQQQNNBBBBBBBBBBBBUUUUUUUUUUUUUUCCCCCCCCCCZUUUUUUUUUUUUMKKKKKKKK
        HCOCCCCGGGGGGGGGWWWWWKKKKQVVQEEETTTTTTTTTEEEEEEGGGGGVPXDDDDDDDDDDCCXXXXXXQHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUUCCCCCCACCCCZUUUUUUUUUUUUOKKKKKKKK
        CCCCCCCGGGGGGGGGGGWWIKKEEEVEBBEETTTTTTTTTEEGGGGGGGGGGPPPPPDDCCCCCCCXXXXXXHHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUMMMMMOOOKKKKKKK
        CCJCWWWWGGGGGGGGGGWIIIKEEEEETBEETTTTTTTTTTTGGGGGGGGGEPBBBBDDBCCCCCCXXXXXXQHQQQZQQVBBBBBBBBBBBBUUUUUUUUUUUCCCCCCCCCCCCCKKKKUUUPPPPOOOOOKKKKKK
        GCCCCGGGGGGGGGGGGGIIIKKEEEEETTTTTTTTTTTTTTGGGGGGGGGGBBBBBBDDBBBCCCCCCRQQQHHHQQQQQVBBBBBBBBBBBBIUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUPPPOOOLOYKKKQQK
        GGGGGGGGGGGGGGGGGGIIIIIEEEEETTTTTTTTTTTTTTGGGGGGGGGBBBBBBBBBBBCCCCCCCRRHHHHHQHHVVVBBBBBBBBIIIIIUUUUUUUUUUCCCCCCCCCCCCKKKKKPPPPPPPOOOYYYQQQQQ
        GGXGGGEGGGGGGGGGIIIIIIIEEEEEETTTTTTTTTTBDTGGGGGGGGGGGBBBBBBBBBCCCCCCCRRHHHHHHHHHVHHHHHIIIIIIIIMMMMUUUUUUCCCCCCCCCCCCCKKKKKKPPPPOOOOYYYYQQQQQ
        GXXGGGGGGGGGGGGGGIIIIIIEEEEETTTTTNTTTTTBDBBBGGGGGGGGGBBBBBBBBBBCCCCCCRLHHHHHHHHHHHHHHIIIIIIIIIIMUUUUUUIICCCCCCCCCCCCCKKKKKPPPPPOOPOYYYYYQQQQ
        XXXXGGGGGGGGGGGGGIIIIIIEEEEETTTTTNNETTBBBBBBGGGGGGGGGGBBBBBBBBBCCCCCCCHHHHHHHHHHHHHHIIIIIIIIIIIMMMMMUIIIICCCCCCCCCCCKKKPPPPPPPPOOPOYYYYYQQYY
        TXXGGGXCCGXGGGGGGIIIIIIEEEEEETTTTNNBBBBBBBBBBGGGGGGGGBBBBBBBBBBCCCCCCCCHHHHHHHHHHHHHIIIIIIIIIDHHMHHMUIIIICCCCIRRRRCCKKKKPPPPPPPPPPPYYYYYYYYY
        TXXXGGXXXXXGGGGGGFITTIIEEEEEEETTNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHHHHHIIIWWIHHMHHHHQHHIIIIIIIIRRRRKKKKNKPUPPPPPPPPPYYYYYYYYY
        XXXXXXXXXFXYFFGGFFFTTTTTEEEEEEENNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHPIIIIIIIWIHHHHHHHHHHIIIIIIRRRRRRKKKNNIINPPPPPPPPYYYYYYYYYY
        XXXXXXXXJFFFFOOGGTTTTTTTTEEEEEEENNNBBBBBBBBBBBBGGGGGBBBBBBBBBBBBBCCCCCHHHHHHHHHHPHPIIIIIWWWBHHHHHHEEIRIIIIILLRRRRRKKKNNNNNPPPPPPYYYYYYYYYYYY
        GXXXXXKXXFFFFFOOOTTTTTTTTEEEEEENNNNBBBBBBBBBBBBBGGGTRRBBBBBBBBBBBCCCCCHHHHHHHHHHPPPIIIIIWWWHHHHHHHEEIIIIIZLLLLLLLLKKKNNNTTTJPPPOYYYYYYYYYRYY
        XXXXXXXXXFFOOOOXXTTTTTTTTEEEENNNNNNNBBBBBBBBBBBBBGGTRTTBBBBBBBBBHHCCHHTHHHHHHHHHPPIIIIIWWWWWHHHHHHHEEIIIILLLLLLLIIIIKINNNTTJPPPOYYYYYYYTYRRY
        XXXXXFXXXFXXXXOXTTTTTTTTTEEEENNNNNBBBBBBBBBBBBBBBBTTTTTBBBBBBBBMMHHHHHHHBHHHHPPPPPPPPIPPWWWWUHHHHHHEEEIILMLLLLLLLIIKKINNNTTTTTTTYYYYZTTTYRRY
        XXXXFFXXFFXXXXXXXXTTTTTTTEEEEMMMMBBBBBBBBBBBBBGGNNTTTTTTTTTBTBBBHHHHHHHHHHHHHPPPPPWPPPPWWWWWWWTHHHEEEIIELLLLLLLLIIIIIITTTTTTTTTYYYYTTTTTTRRR
        XXXOXFFXFXXQXXXXXXXTTTTTTEEMMMMMMMBBBBBBBGGGGGGGGGTTTTTTTTTTTNNHHHHHHHHHHHHHPPPPPPWWPWWWWWWWWWWEEEEEEEEELLLLLLLLLIIITTTTTTTTTTRYYYYQTTTTRRGR
        XXXXXFFFFFXXXXXXXTTTTTTTTTTTMMMMMMBBBBBBLLLGGGGHGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPPPCCCWWWWWWWWWWWWWEEEEEEELLLLLLLLLLILLOTTTTTTTTTTTYQQQQTTTQRRR
        XXXXFFFFFFXXXXXXTTTTTTTTTTTTTTMMMMBBMMLLLLLGGGGGGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPCCCCCRWWWWWWWWWWEEEEEEEEELLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTTQQRQQ
        FFFFFFFFFFXXXXXXTTTTTTTTTTTXTTTMMMMMMMLLLLGGGGGGGGTTTTTTTTTTTTNVHHHHHHHHHHHPCCCCCCCCCWWWWWWWWEEEEEEEEEEVLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTQQQQQQ
        FFFFFFFFXXXXXXXXTTTTTTTTTXXXTSTXXMMMMLLLLLLLGGLTTTTTTTTTTTTTTVVVHHHHHHHHHHHCCCCCCCCCWWWWWWWWWWWWEEEEVVVVVVLVVLLVVVBBWWTTTTTTTTTTTTQQQQQXQXXQ
        FFFFFFFFFXXXXXXXXTTTTTTTTTXXXXXXXXMMMMMLLLLLLOLDDDDDTTTTTTTQQQQQHWHHHHHHHCCCCCCCCCCCCWWWWWWWWWWWEWWEVVVVVVVVVVLVVVBBBWTTTTTTTTTTTTQQQQQXXXXX
        FFFFFFFFFFXXXXXXJJTTTTTTTMXXXXXXXXXMIIMLLLLLLLLDDDDTTTTTTQQQQQQHHHHHHHHHHCCCQCCCCCCCWWWWWWWWWWWLWWWVVVVVVVVVVVVVVVPBBWTTTTTTTTTTTTQQQQQQQXXX
        FFFFFFFFFFFXXXXJJTTTTTTTTMMXXXXXXXIIIILLLPLLDRDDDDDTTTTQTQQQQQEHHHHHHHHHHHHCCCCCCCZCWWWWWWWWWWWWWWWVVVVVVVVVVVVVVBBBBWTTTTTTTTTTTTQQQQQQQQXX
        FFFFFFOFFFOIXIJJJJJJJJJJJXXXXXXXXXIIIIIELPLLDDDDDDDDTTQQQQQQQQEEHEEHHHHHHRRRRRCCCCZCEEWWWWWWWWWWWWWVVVVVVVVVVVVVVVBBBBTTTTTTTTTTTQQHHHQQQQXQ
        FFFFOOOOOOOIIIIJJJJJJJJJJXXXXXXXUIIIIIIELILLDDDDDDDDTTQQQQQQQQEEEEHHHHVVVVVRRRCCJJJJJJWJJWWWWSDDWWWVVVVVVVVVVVVVBBBBBBBBTBBBBTTRTHHHHHHHHQXQ
        FFFFFFFOOOIIIIIJJJJJJJJJXXXXIXXUUIIIIIIIIIIIEDDDDDDDQTQQQQQQQQEEVVVVVVVVVVVRRRCCJJJJJJMEEWWWSSSDSSWVVVVVVVVVVVVBBKBBBBBBBBBBBTTRRHHHHHHHQQQQ
        FFFFFFOOOIIIIIYZJJJJJJJJIEIXIXUUUUIIIIIIIIIEEEEDDDDAQQQQQQQEEEEOVVVVVVVVVVVRRRCCJJJJJJJETTTTSVSDSSSVVVVVVVVVVVVBBBBBBBBBBBBBRRRRHHHHHHQHQQQQ
        FFFFFFFOOOIYYYYJJJJJJJJIIIIIIUUUUUIIIIIIIIIEEEDDDDAAAQQQQQQEEEOKVVVVVVVVVVVRRRRRJJJJJJJEEETTSSSSSSSVVVVVVVVVVBBBBBBBBBBBBBBRRRRDHHHHHHQQQQQQ
        FFFFFFFOOOOOYYYYYYYYJJIIIIIIIUUUUPIIIIIIIIIEEEDEDDDAAQQQQQQOEOOOOOOLXXVVVVVRRRRJJJJJJJOEEEEESSSSSSSSSVVVVVVVVBBBBBBBBFBFBBBBBDDDDDHHQQQQQQQQ
        FHHFFOOOOOOOOYYYYYJJJJIIIIIIPUUUPPPPIIIIIIQQQEEEEDAAAAAQXQOOOOOOOOOOXXVVVVVRRRRJJJJJJJJEEEESSSSSSSSSVVVVVVVVJBJJBBBBBFFFBBBTTTDDDDHHQQQQQQQQ
        HHHHFOOOOOOJOYYYYYJJJJIIIIIPPPUPPPPPIIIIIQQPPQQAAAAAAAXXXXOOOOOOOOOOXXVVVVVRJJJJJJJJJJJEEEESSSSSSSSVVVVVVJJJJJJJBBBBFFFFFBBTDDDDDDHHHQQQQQQQ
        HHOOOOOOOOOOOYYYYYJJJJIIIIIIPPPPPPPPQQQQQQQQQQQAAAAAAAXXXXOOOOOOPOOOOXXXXXXRRJJRJJJEEEEEEEEEEESSSSSSVVVVVJJJJJJJJBBBFFFFFFBTDDDDDDDMQQQQQQQQ
        HHHOOOOOOOOJJJJYJJJJJGGGIIIIPPPPPBPQQQQQNQQQQQQQQAAAAAAXXXOOOOOOOOOXXXXXXXRRRRRRJJJJEEEEEEEEEEESSSSSSVVVVDJAJJJJJJFFFFFFFFSDDDDDDDDQQQQQQQQQ
        HHHHOOOOOOOJJJJJJJJJJGGGGGIPPPPPPBBQQQQQNNNNQQQQQAAAAAAAAXOOOOOOOOOXXXXXXXRRRRRRRRJEEEEEEEEEEEEEESSSSSVVSSAAJJJJJJFFFFFFFFDDDDDDDDDQQQQQQQQQ
        HHHHHOOOOJJJBBBBBJJJGGGGGIIIPPPPPBBQQQQQNNNDQQLAAAAAAAAAXXXOOOOOOOXXXXXXJXRRRRRRREJEEEEEEEEEGEEEESSSSSSSSSSSBJJJJJJSFFFFFFFFDDDDDDDQQQQQQQQQ
        HHHHHHHHHHJJBBBBBBBGGGGGGGIIIIPPPBBBQQQQNDNDQQLLAAGAKKKKXXXXXONOOOXXXXXXJXXRRRRRREEEEEEEEEEELEKEELSSSSSSSSSYJJJJJJJSFFFFFFLDDDDDDQQQQQQQQQQQ
        HHHHHHHHBJJJBBBBBBBGGGGGEIIIIIPPPPBQQQQQDDNDLLLLLGGGGKKKXXXXXKNNOOXXXXXXJXRRRRRRRUEEEEEEEEELLLLEILLLLSSSSSSYJJJJJJJYFJJJFJJJDDDDDDQQQQQQQQQQ
        HHHHHHHHBBBBBBBBBBBGGGGGGGGIIPPPPPPDDQQQDDDDLLLLLGGGGKKKKKXXXKNOOOJJJXJJJRRRRRRRREEEEEEEEELLLLLLLLLLLSSSSSSJJJJJJJJYYJJJJJJWDDDDDDQQQYYYQQQQ
        HHHHHHHBBBBBBBBBBBBBGGGGGGGBBBBBPPDDDDDDDDDDLLLZLLGGGKKKKKKKKKNNNOJJJJJJJRRRRRRDDDDDEEEEEELLLLLLLLLLLLLSSSJJJJJJJJJYYYJJJJJJDDDKQQQQYYYYYQQQ
        HHHHHHBBBBBBBBBBBBBBGGGGGGGGBBBBMMDDDDDDDDDDLLLLLGGGGKKKKKKKKKNJJJJJJJJJJJRRRRRDDDDDDDELLELLLLLLLLLLLLLLLSCCAJJJJJYYYJJJJJJJJJDGQQGGYYYYYQQQ
        HHHHHHHHBBBBBBBBBBBBGGGGGGGGGBBMMDDDDDDDDDDLLLLLLGKKGKKKKKKKKKNJJJJJJJJJJJJRRRDDDDDDDEELLLLLLLLLLLLLLLLLASACAAAYJYYYYYYJXJJJJKGGGGGGGAYYQQQQ
        HHHHHHHBBBBBBBBBBGGGGGGGGGGBBBBMMMDDDDDDDDDDLLRLXXKKKKKKKKKKKKNNUUJJJJJJJJJRRRRDDDDDDELLLLLLLLLLLLLLLLLAAAACAAAYJYYYYYYJXXEEJGGGRRRRAAYYIQQQ
        HHHHHHBBBBBBBBBBBGGGGGGQQQGQBQQMMMDDDDILLLDLLLLLXXXKKKKKKKKKKNNNNUUJJUUJJJJJRJJJDDDDLLLAAAAALLLLLLLLLLIAAAAAAAAYYYYYYYXXXXXEEEGGRRRRGAYQQQQA
        HHHHHHBBBBBBBBBBBBGHGGGQQQQQQQQMMMIIIIILHLLLLLQQXXXXXKKKKKKKKKNNNUUUUUUJJJJJJJJJJJDAAAAAAAAAALLLLLLLLAIAAAAAAAAAYYYYYXXXXXXGGGGGRRRRGAAAAAAA
        HHHHHHHBBBIBBBBBBHHHGQQQQQQQQQQMIIIIIIIIIILLDDXQXXXXXXJJKKKKKKNNNNUUUUUUUUJJJJJJJAAAAAAAAAAAALLLLLLLLAAAAAAAAAAYYYYYYYYYYXXGGGGGRRRRGAAAAAAA
        HHHHHHHHHIIIBBHBBHHHQQQQQQQQQQQMMIIIIIIIIIILIIXXXXXXXJJJKJJKKKNNNUUUUUUUUJJJJJJJJJGGAAAAAAAAALLLLLLLAAAAAAAAAAAAYYYYYYYYYYYYGGGGRRRRAAAAAAAA
        HHHHHLLHHHHHBBHHHHHQQQQQQQQQQQQQIIIIIIIIIIIIIICCCCCCCCCJJJJJJUUUUUUUUUUUDUJJJJJJJGGAAAAAAAAAALLLLLLZOOAAAAAAAAAAAYYYYYYYYYGGGGGGRRRRGAAAAAAA
        HLHHLLLLHHHHHHHHHHHHFQQQQQQQQQQQQIIIIIIIIIIIIICCCCCCCCCJJJJJJOOUUUUUUUUUUUJJJJJJJJAAAAAAAAAAALDDVVLZOOOAAAAAAAAAAYYYYYYYYYYYGGVGRRRRPAAAAAAA
        HLLHLLLDHHHLHHHHHHHHQQQQQQQQQQQQQIIIIIIIIIIIHICCCCCCCCCJJJJJJJJJJUUUUUUUUUJJJJJJJJIIIAAAAAAAAXDDVVVOOOOAAAAAAAAAAAAYYYYYYYYYKKGGRRRRPAAAAAAA
        HHLLLLLLLLHLLHHHHHHHXQQQQQQQQQQQUUIIIIIIIIIIHICCCCCCCCCCCCCJJJJJJUUUUUUUUUJJJJJJJJJIIAAAAXYXXXXXVVVVOAAAAAAAAAAAAAAYYYYYYCCCKKGGRRRRPPPPZZZA
        LLLLLLLLLLLLLHYHHHHHXQQQQQQQQQQQUIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUUUMPJSJIIIIIIACXXXXXXXXVVVVAAAAAAAAAAAAAAYYYYYYYCCCKKRRRRRRPPPPMZZZ
        LLLLLLLLLLLLLLYYYYYYXXXXQQQQQQQIIIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUMMMMSSSISIIIICCCXXXXXXXXVVVVVVVAAAAAAAALLYYYYYCCCCCCCPPPPPPPPPPZZBZ
        LLLLLLLLLLLLVYYYYYYYXXXXXQQQQQQIIIIICCIIIIIIIICCCCCCCCCCCCCCCJJJJUUUUUMMMMMMMMSSSSSSSICXXXXXXXXXXXXXVVVVAAVAAALLLLYYYYYCCCCCCCCCPZPPPPPPZZZZ
        LLLLLLLLLLLLVYYYYYYXXXXXQQQQQQIIIIIIIIIIIIIIMIGGGGGGGUCCCCCCCJJJJJUUUUMMMMMMMSSSSSSSSSSUXXXXXXXXXXXVVVVVAAVAVAALVCYYYYCCCCCCCCCCPPPPPPPPPPOO
        LLLLLLLLLLLLYYYYYYXXXXXXQQQYIQIIIIIIIIIIIIIIMGGGGGGGGGCCCCCCCJJJJJJJUUMMMMMMSSSSSSSSSSSSXXXXXXXXXXXVVVVVVVVVVVVVVCYYYYCCCCCCCCCCPPPPPPPPPOOO
        LLLLLLLLLLLLYYYYYYXXXXXXXQXIIIIIIIIIIUIIIIIIMGGGGGGGAACCCCCCCJJJCJUUUUMMMMMMSSSSSSUSSSSFXXXXXXXXXXXVVVVVVVVVVVVGVCGGGEEECCCCCCCCCPPPPPPPPOOO
        LLLKLLLLLLLYYYYYYYXXXXXXXQIIIIIIIIIIIUUIIIMMMGGGGGGAAWWWWJJJJJJCCJUUUUMMMMMMSSKKKSUSSSSXXXXXXXXXXXXXVVVVVVVVVVVGCCGGEEEEFCCCCCCCCPPPPPPPPOOO
        LLKKLLYLLLYYYYYYYYLLXXXXXXXXIIIIIIIIIUMMMIIMMMGGMMGAAAWWWJJJJJJJCCCMMMMMMMMMMMKKKKWWWZZXXXXXXXXXXXXVVVVVVVVVXGVGGGGEEEEEFCCCCCCCCPPPPPPPPOOO
        LKKKKYYYYYYYYYYYYYSLXXLXLLIIIIIIIIIIIUMMMMMMMMMMMGGAAWWWWJJJJJJCCCCCCMMMMMMMMKKWKWSWWZZXZZXXXXXXMMXVVVVVVVVXXGGGGEGEEEEEFCCFCCCCCPPPPYYROOOO
        LKKKKKYYYYYYYYYYYYYLXXLXLLIIIIIIIIYYYYMMMMMMMMMMMWWAAAWWWWJJJJCCCCCCMMMMMKKKKKKWWWWWWZZZZZXXXXXXMVVVVVVVVVVXXGXEEEEEEEEEFFFFCCFPPPPPPRRRRROO
        KKKKKKKYYYYYYYYYYLYLLLLLLLLIIIIMIIIYYYMMMMMMMMMMMWWWWWWWWWCJJCCCCCCCMMMMKKKKKKWWWWWWWZZZZZXXRXXRMVVVVVXXXXXXXGXXEETEEEEFFFFFFFFPPPPPPPRRRROR
        KKKKKKYYYYYYYYYYYLLLLLLLLLIIIMMMMIMMYYYMMMMMMMMMMMWWWWWWWWCCCCCCCCCCMMDKKKKKKKWWWWWWWWZZZZXXRRRRRRRVVVVVLXXXXXXXXETFFFFFFFFFFFFFPPPPPRRRRRRR
        KKKKKKYYYYYYYYYYYLLLLLLLLLMMMMMMMMMYYYYYMMMMSSMSMSWWWWWWWCCCCCCCCCCCMMDCFCKKKWWWWWWWWWZWWZZRRRRRRRRVVVXXXXXXXXXXXXXXFFFFFFFFFFFPPPPPPRRRRRRR
        KKKKKKKYYYYYYYYYLLLLLLLLLLLLLMMMMMMMMYYSSSSSSSSSSSWWWWWWWCCCCCCCCCCCCCCCFCKKKKWWWWWWWWWWZZZZRRRRRRRVVVHXXXXXXXXXXXXXXFFFFFFFFFFFPPFIIIRRRRRR
        KKKKKKKKYYYYYYYYKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSWWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKWRRRRRRRHRRRRVHHXXXXXXXXXXXXFFFFFFFFFFFFFFFFIIIRRRRRR
        KKKKKKKKKKYYKYYKKKLLLLLLLLLLMMMMMMMMMSSSSSSSSSSSSSWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWWKKRCRRRRHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIRRDR
        KKKKKKKKKKKKKKKKKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSRRRRWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKKKKRRRRRHHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFIIIIIIIIRDD
        KKKKKKKKKKKKKKKKKKLLLLLLLLLLMMMMMMMMMRSSSSSSSSSSSSRRRRRRRVVCCVVVVVCCCCCCCKKKKKKKKWWKKKKKKKRRRRHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIIIDD
        KKKKKKKKKKKKKKKKKKLKLLLLLLLMMMMMMMMMMMKSSSSSSSSSSSSSRRRRVVVVVVCCCCCCCCCCCKKKKKKKKKWKKKKKKKRRRRRHHHHHHHXXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIDDD
        KKKKKKKKKKKKKKKKKKKKKKKLMMMMMMMMMMMMMMKSSSSSSSSSSSSRRRRRRRRVCCCCCCCCHHCCCKKKKKKKKKKKKKKKRRRRHHHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIIDDD

        """;
}
