namespace AdventOfCode.Puzzles.Day12;

using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using NUnit.Framework;

[MemoryDiagnoser(false)]
[SimpleJob(RuntimeMoniker.Net90, baseline: true, iterationCount: 20)]
public class Puzzle1
{
    [Test]
    [Benchmark]
    public void Solve()
    {
        var grid = PuzzleInput
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .Select(x => x.ToCharArray())
            .ToArray();
        var rows = grid.Length;
        var cols = grid[0].Length;

        var visited = new bool[rows, cols];
        var directions = new[] { (-1, 0), (0, 1), (0, -1), (1, 0) };
        var result = 0;

        for (var i = 0; i < rows; i++)
        {
            for (var j = 0; j < cols; j++)
            {
                if (!visited[i, j])
                {
                    var area = 0;
                    var perimeter = 0;
                    var type = grid[i][j];
                    var queue = new Queue<(int x, int y)>();

                    queue.Enqueue((i, j));
                    visited[i, j] = true;

                    while (queue.Count > 0)
                    {
                        var (x, y) = queue.Dequeue();
                        area++;

                        foreach (var (dx, dy) in directions)
                        {
                            var nx = x + dx;
                            var ny = y + dy;

                            if (nx >= 0 && nx < rows && ny >= 0 && ny < cols)
                            {
                                if (grid[nx][ny] == type && visited[nx, ny] is false)
                                {
                                    visited[nx, ny] = true;
                                    queue.Enqueue((nx, ny));
                                }
                                else
                                {
                                    perimeter++;
                                }
                            }
                            else
                            {
                                perimeter++;
                            }
                        }
                    }

                    result += area * perimeter;
                }
            }
        }

        Console.WriteLine(result);
    }

    private const string PuzzleInput = """
        DDDDDDDAAAAAAAAAAAAAAAAIIIIIIIIEEEEEEEERRRRRBBBBBRRRRRRRRRRRRIUUUIXIIIIIPPPPPPPPPPPPPPWWPPPPPPPPXXXXHXXUUUUUUUUUUUUUUUPWWWWWWWWWCJJJJJJZZZZZ
        DDDDDDAAAAAAAAAAAAAAAAAAIIIIIIIIEEEEEERRRRRBBBBBBBBRRRRRRRRRIIUUUIIIIIIIPIPPPPPPPPPPPPPWPPPPPPPXXXXXXXXUUUUUUUUUUUUUUUPWWWWWWWWWJJJJJJJZZZZZ
        DDCCCCCAAAAAAAAAAAAAAAAAAIIIIIIEEEEEEERRRRRBBABBBBBRRIRRRRRRIIIIIIIIIIIIIINNPPPPPPPPPPPWPWWWPPPXXXXXXXXUUUUUUUUUUUUUUUPPPWWWWWWWJJJJJJZZZZZZ
        DDCCCCAAAAAAAAAAAAAAAAAAAIIIIEEEEEEEEERRRRRBBBBBBBBRRIRRRIIIIIIIIIIIIIIIINNPPPPPHPHHPPPWWWWWWWXXXXXXXXVVUUUUUUUUUUUPUPPPPPWWWWWJJJJJJJZZZZZZ
        CCCCCCCAAAAAAAAAAAAAAAAAEIIIIIIIEEEEEERRRRRRBBBBBBBIIIIIIYIIIIIIIIIIIIIIINNNPPPPHHHHPPWWWWWWWYXXXXXXVVVUUUUUUUUUUUUPUPPPPPPWWWWJJJJJJJJZZZZZ
        CCCCCCCATTAAALAAAAAEEAAEEIIIIIIIEEEEEERRRRBBBBBBBBBIIIIIIIGDGIIIIIIIIINNNNNNPPPHHHHHPPWWWWWWXXXXXXXXVVVVVUUVUUUUUUUPPPPPPPPPPWWJJJJJJJJJZJZZ
        CCCCCCCATTAAALAAAAAEEEEEEEIIISIIIEEEEEERRRBBBBBBBBIIIIIIIIGGGGIIIIIINNNNNNNNPPPPHHHHWWWWWWWWWWXXXXVXVVVVVVVVVUUUUUPPPPPPPPPPPWJJJJJJJJJJJJZZ
        ZCCCCTTTTTAANAAAAAAEEEEEEEIIIIIIUEEEERRRRBBBBBBBBBIGIIIIIDGGGGGIIIIINNNNNNNNPPHHHHHHHWWWWWWWWXXXXXVVVVVVVVVVVUUUUPPPPPPPPPPPSJJJJJJJQJJJJJZZ
        CCCCCCCTTTATAAAAMEEEEEEEEUIUIIUUUUEEERRRBBBBBBBBBBDDIIIIIDGGGJGIIIIIINNNNNNNNNNTHHHHHWWWWWWWWWXXXXVVVVVVVVVVUUUUUPPPPPPPPPPPPSSUUJJJQJJJJJZZ
        CCCCCCTTTTTTAAAAEEEEEEEEEUUUUUUUUUUEEEUUUUBBBBBBBBBDIIDDDDGGGGGGIIIIINNNNNNNNNNTHHHHHHWWWWWWBWXVVVVVVVVVVVVVVVUUPPPPPPPPPPPPPSPUUJJJQKJJMJZZ
        CCCCCCCTAAAAAAAAAEEEEEEEUUUUUUUUUUUUUUUUUUBUBBBBDDDDDDDDDDGGGGIIIIISNNNNNNNNNNNNHHHHHWWWWWWBBWCVZZVVVVVVVVVVVVUUPPPPPPPPPPPPPPPUUUUQQQAQQQZZ
        CCCCCCCAAAAAAAAAEEEEEEEGUUUUUUUUUUUUUUUUUUUUUBBBDDDDDDDDDDGGGGGRPPPPPPNNNNNNNHHHHHHHWWWWWWWWWWWZZZZVVVVVVVVVVVVVFPPPPPPPPPPPPPPUUUUBQQQQQQQZ
        KCCCCKAAAAAAAAAAAEEEEEEEEUUUUUUUUUUUUUUUUUUUUBBDDDDDDDDDDDDGGGPRPPPPPNNNNNNNNHHHHHHHHWWWWWWWZZZZZZZVVVVVVVVVVVVVVPPPPBBPPPPPPIIUUUBBQQQQQQQQ
        KKCCCKAAAAAAAAAARRAPENNNPUPUUUUUUUUUUUUUUUUKDDDDDDDDDDDDDDDGPGPPPPPPNNNNNNNNNHHHHHHWWWYWWWWZZZZZZZZZZVVVVVVVVVVVQQBBBBBBPPPPPPIUUUUBBQQQQQQQ
        KKCCKKAYAAAAAAAAAAAPENNNPPPPUUUUUUUUUZZZZZKKKDKDMMDDDDDDDDDDPPPPPPPPPPNNNNNNNNHHHHHHWYYWWWWWWZZZZZNZZVVUVVVVVVQVQQQBBBBPPPPPPPJUBBBBQQQQQQQQ
        KKKKKKAAAAAAAAAAAAAPENNNPPPPPUUJUUUUZZZZZZKZKKKDDDDDDDDDDDDDPPPPPPPPPPIINNNNNHHHHPHHWWWWWWWWWZZZNNNZZZVUUUUUVVQQQJJQQQBBPPPMPJJJJJJQQQQQQQQQ
        KKKKKKAAAAAAAAAAAAPPPNNNPPPPPPPJUUUZZZZZZZZZZKKDDDDDDFDDDDDPPPPPPPPPPPNNNNNNNHPPPPHWWWWWWWWWWZZZNNNNNNVUUUUUUQQQQQQQQQQBBRRRRRJJJJJQQQQQQQQQ
        KKKKKKKKATAAAAAGJPPPJNNNJJPMPPJJJUUUZZZZZZZZZKKDDDDDDFDDDDDDPPPPPPPPPMMMNNNZNNPPPPWWHWWPWWWWNZZZNNNVVNVUUUKKQQQQQGGQQRQRRRRRRRJJJJJJJFQQFFFF
        KKKKKKKKKTTAAAGGJJJJJNNNJJJJJPJJJUUUUZLZZZZZZKKDDDDFFFDDDDDDDVPPPPPPPPPMNNNNCCCCPPPWHPPPWWWWNNNNNNNVVNVVVUKKQQQQQRGRRRRRRRRRRRRERJJJJFFFFFFF
        KKKKKKKKKTTTTTGGGJJJJNNNJJJJJJJJOUUUUUZZZZZZZKKDKKDFFFFFFDDDDPPPEPPXPZPMMMMMMMMCPPPPPPPPWPWWNNNNNNNVVVVVVUKKKQQQRRGRRRRRRRRRRRRRRRJZBFFFFFFF
        KKKKKKKKKTTTTTTGGGJJJNNNJJJJJJJFOOUUUUZZZZZZZKKKKKDPFFFFFFFFEEEEEDDDMMMMMMMMMMMMPPPPPPPPPPPWNNNNIINVVVVVVVKKKKBBBRGRRRRRRRRRRRRRRRRBBBFFFFFF
        KKKKKKKTKTTTTTTTTJJJJNNNJJJJJJJFOOUAUNNZZZFFZKKKHKHPFFFFFFFFEEEEEEDDDDDMMMMMMMMUPPPPPPPPPPPPPNNIIIVVVVVVVBBBKKBBRRRRRRRRRRRRRRRRRRSBBBBBFFFF
        KKKKKKTTKKTTKKKKGJJJJNNNJJJJJJJOOOOAUNNZZFFFFKKKHHHHFFFFFFFFEEEEEDDDDXXXXMMMMMMPPPPPPPPPPPPPQHNIIIVVVVVVVBBBBBBBBRRRRRRRRRRRRRRRRRRBBFFFFFFF
        KKKKKKTTTTTTKKKMMJJJJJJJJJJJJJJJOOOONNNNZNNNHHHHHHXXFFFFFFFEEDEEDNDDDDXXXXMMMMMMPPPPPPPPPPPPQHNIIVVVVVVVVBBBBBBBBBRRRRRRRRRRRRRRRRBBBBBFFFFF
        KKKKKKKTTTKKKKKMMRJJJJJJJJJJJJJJOOOOONNNNNNHHHHHHHXXFIFFFFFFDDDDDDDDDDXXXXXXMHHHPPPPHHPPPPPQQHHIIVVVVVVVVBBBBBBBBBRRFFRRRRRRRRRRRBBBBBBBFFFF
        KKKKKKKKMTKKKKKMMMJMMMMJJJJJJJJOOOOOONNNNNNHHHHHHHHHFFFFFFDRDDDDDDDDDXXXXXXXMHHHPPPPHHPPPPPPHHHIIVZZZZZBBBBBBBBBBBRKFFFFRRRRRRRBRRRBBBBBBFFF
        KKKKEEKMMOKKKJMMMMMMMMMJJSJJJJJOOOOOOONNNNGHHHHHHHHIFFFFFDDDDDDDDDDDDXXXXXXXXXHHHHPHHHHPPPPPHHZIIZZZZBBBBBBBBBBBFFKKFFFRRRFRFFFBBRRBBBBBBBBF
        KKKKKOOOMOKKKOMMMMMMMMMMMSJJJJJOOOOOOONNNNGHHHHHHHHHFFFFDDDDDDDDDDDDDDDDXXXXXXHHHHHHHHHPPPHHHHZIIZZBBBBBBBBBBBBBFFFFFFFFFFFFFFBBBBBBBBBBBBBB
        KKKKKOOOOOKKOOFMMMMMMMMMMMJJJJOOOOOOOONNNNGHHHHHHIHLFFFFFDZDDDDDDDDDDDDXXXXXXXXHHHHHHHHHPPHHHOZIZZZZZBBBBBBBBBBBFFFFFFFFFFFFFBBBBBBBBBBBBBBB
        KKKKOOOOOOOOOOMDMMMMMMMMMMFFJOOOOOOZZZNZNZGHHHHHHHHLFFFFFDDDDDDDDDDDDDDXXXXXXXXXXXXHHHHPPPHHHZZZZZZZZBBZZWWBBWWFFFFFFFFFFFFFFBBBBBBBBBEEEBBB
        KEOOOOOOOOOOOOMMMMMMMMHMMMIFFFOOOOOOZZZZZZGHHHHHHHHFFFFFFFDDDDDDDDDDDXXXXXXXXXXXHXXHHHHHHHHHHZZZZZZZZZBZZQWWWWWFFFFFFFFFFFFFFFBFBBBBBVEEBBBE
        EEOOOOOOOOOOOOMMMMMMMMHHIIIBFOOOOOOOZZZZZZGGGHBVYHHFFFFFFFPPDDDDDDDNNNXXXXXXXXXXHXHHHHHHHHHHHWZZZZZZZBBZZWWWYWWFFIFFFFFFFFFFFFFFDDBBBBBEEEEE
        EEOOOOOOOOOOOOXMMGMMZMMHIIZUUUOUUUOUUZZZZZGCVVVVVVHFFFFFFPPPDDDDDDNNNNXXXXNCXXXXHXHHHHHHHHHHHZZZZZZZZZZZZZWWWWWFFFFFFFFFFFFFFFFFDDDBBBBEEEEE
        EEEOOOOOOOOOOOOGGGMGMMHHHUUUUUUUUUUUUUZUZUCCCCVVVVEEAAFFFPPPZDDDDNNNNNNXNXNCCXCVHHHHHHHHHHHHZZZZZZZZZZZZZZWWWWWFWFFFFFFFFFFFFFFFDDDBBBBEEEEE
        EEEOOOOOOOOOOOOGGGGGMMHUUUUUUUUUUUUUUUUUUUUUCVVVVEEEEAAFPPPPZDDDNNNHNNNNNNNNCCCVCCCCHHHHHHHHZZZZZZZZZZZZZWWWWWWWWWWWFFFFZZIIIFZIIIIBEEEEEEEE
        EEEEOOOOOOOOXXGGGGGGGMMUUUUUUUUUUUUUUUUUUUUUCVVVCEEPPAAAPPPPZDDNNNNHNNNNNCCCCCCCCCCCCHHHHHHHZZZZZZZZZZZZZLWWWWWWWWWWFFFFIIIIIFFIIIOEEEEEEBEE
        EEEEEEOOOOOOXXGGGGGGGGGGGUUUUUUUUUUUUUUUUUUCCVVVEEEPPPPPPPPPPJDDNNHHNHNNCCCCCCCCCCCCCHHHHHHZZZZZZZZZZZZZZZWWWWWWWWWWFFTFTIIIIIIIIIIIEEEBEBEE
        EEEEEYYYOYYOXXXGGGGGGGGGGUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJJJIIHHHHNCJCCCCCCCCCCCCCCHHHHIIIIZZZTTZZDDZVJJJWWWWWWFFTTTTTIIIIIIIIIEEEBBBBBB
        EEEREEYYYYYXXXTGGGGGGGGGKUUUUUUUUUUUUUUUUCCCCCCCCCEEPPPPPPPPPJIIISSHHCCCCCCCCCCCCCCCCCCCAHHHIIIIZZTTTTJJJJJJJWWWWWWFWWWIIIIIIIIIIIIIEEBBBBBB
        HEEEEEYYYYXXTTTGGGGGGGGKKKKGUUUUUUUUAUUUCCCCCCCCCCCPPPPPPPPPJJIIISHHHHHHHCCCCCCCCCCCCCCCAAHHHIIIZEITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIIIWBBBBBBB
        HHHHHYYYYXXXXTTTGTGGGGKKKKKUUUUUUUULAAAAAWWWWWWWCCPPPPPPPPPPJJJIITHHHHHHCCCCCCCCCCCCCCCAAAAIIIIIIIITTTTTJJJJJJJWWWWWWWIIIIIIIIIIIIIIBBBBBBBB
        HHHHYYYYYYXXXTTTGTGGGGKKKKKKLLUUAUULAAAAAWWWWWWWWWWWPPPPPPPPPPTTTTHHHHHHCCCCCCCCCCCCCAAAAAAAIIIIIIIITTTTJJJJJJJWWWWWWWWIIIIIIIIIIIIICCBBBBBB
        HHHHHYYYYYYTTTTTTTTTTGGKKKKLLLULAAAAAAAABWWWWWWWWWWWPPPPWWPTPTTTTTTHHHHHCCCCCCCCCCCCCCAAAAAIIIIIIIIITTTTJJJJJJJWWWWWWVVIIIIIIIIIIIIIIIBBBBBB
        HHHHHHHHYYYUTTTTTTTTTTTTTCKKLLLLAAAAAAAABWWWWWWWWWWWPPWWWWWTPTTTTTTHHHHHHTCCCCCCCCCCCAAAAAIIIIIIIIIITTTJJJJJJJJWWWWWVVVIIIIIIIIIIIIIIBBBBBBB
        HHHHHHHHYYYUUTTTTTTTTTTUUKKKLLLAAAAAAAAAAWWWWWWWPPPPFFWWWWWTTTTTTTTHHHHHHTTTTTCCCCCAAAAAAAAAIIIIIIIIITTTJJJJJJJPWWWVVVVVVVIIIIIIIBBIBBBBBBBB
        HHHHIHIHYHHUUTTTTTTTTTTTTEKLLLLLAAAAAAAPJWWWWWWWPPPPFFWWWWWTTTTTTTTTTHHHHTTTTTCCCCJAAAAAAAAAIIIIIIIIIITTTJJPJJJPPWWVVVVVVVVIIIIIBBBBBBBBBBBB
        HHIIIIIHUUUUUUTTTTTTTTTTEEKWWLLLACAGAAAPPWWWWWWWPPPFFFFWWTTTTTTTTTTTTHHHTTTTTTTTTQJAAAAAAAAAIIIIIIIIIITCTTJPPPPPPPPVPVVVVVVTTTIIBBBBBBBBBBBB
        IIIIIIZUUUUUUTTTTTTTTTTTTTPWWWPPPPBAAPPPPWWWWWWWPPPFFFFFFLLLLTTTTVTTTTTTTTTTTTTTTQQLAAQQAAQIIIIIIIIICCCCTPPPPPPPPPPPPVVVEVEETTIIBBBBBBBBBBBB
        IIIIIIZUUUUUTTTTTTTTTTTTTDWWWWWPPPBBPPPPPWWWWWWWPFFFFFFLLLLLLLEVETTTTTTTTTTTTTTTTTQQWQQQQQQLIIIIYIIPPPCCCCPPPPPPPPPPEVVVEVEETTIIPBBBBBBBBBBB
        IIIIIIIIUUUUUUTTTTTTTTTTTWWWWWPPPBBBPPPPPPPPPPPPPPFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQIIIIYNIPPPPPCCCPPPBPPPPPEEEEEEETTTITPBBBBBBBBBBB
        IIIIIIKKUUUUUUTUUTTTGTGGGWWQWWPPPBBBPPPPPPPPMMPMPFFFFFLLLLLLLLEEEEEETTTTTTTTTTTTTQQQQQQQQQQQQQQYYNNNNPPCCCCCPPBPPPPPEEEEEEETTTTTBBBBBBBBBBBB
        IIIIIIIIUUUUUUUUTTTTGGGGGWJWWPPPPBBBBPPPPPMMMMMMMFFFFFLLLLLLLLEEEEEEEEEAATTTTTQTTQQQQQQQQQQQQQQQYNNNPPPCCCCCCCBBPPPEEEEEEEEETTTTBBBBBBBBBBJJ
        IIIIIIIIUUUUUUUUTTTTGGGGGWWGPPPPPPPBBPBPEPJMMMMMFFFFFFFLLLLLLLLEEEEAAEAAATAAQQQQQQQQQQQQQQQQQQHHYNNNPPPCCCCCCCCBPPPEEEEEEEEEETTTTBBHBBHHBBBB
        IIIIIIIUUUUUUUUUTTTGGGGGGGGGGPPPPPPBBBBMMJJMMMMPPFFFFFFFLLLLLLEEEEAAAAAAAAAAAQRQQQQQQQQQQQQQQHHHHJNPPPPPGGCCCCCPPPEEEEEETTTEETTTTHHHBHHBBBBB
        IIIIIIUUUUUUUUUUUUWWGGGGGGGGGPPPPPPPMBMMMMMMMMMMMFFFFFFLLLLLLLEAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPPJGGCCCCGGGEEEEETTTTTTTTTTTHHRHHHBBBB
        MIIIIIUUUUUUUUUUUUWWWGGGGQQGGGPPPPPPMMMMMMMMMMJJJFFFFFLLLLLLALAAAAAAAAAAAAOOOOOQZZQQQQQQQQQQHHHHHHPPPPPGGGGCGGGGGGEGGEETTTTTTTTTTHHHHHHHHBBB
        IIIIIOUUUUUUUUUUUWWWWWQQQQQGPPPPPLPMMMMMMMMMMMMJJJFFXXLLLLAAAAAAAAAAAAAAAAOOOOOZZZZQQBBBBBBBWWHHHPPPPPPGGGGGGGGGGGGGTTTTTTTTHTHHHHHHHHHHBBBB
        IIIILUUUUUUUUUUUWWWWWGQQQQQQQQPPPLPMMMMMMMMMMMMJJJJFXXXXLLLLAAAAAAAAAAAAAAOOOOOYBBBBBBBBBBBBWWWHHPPPPPGGGGGGGGGGGSSSTTTTTTTTHHHHHHHHHHHHHBBB
        SIIILLUUUUUUUUUWWWWWWGQQQQQQQQQPQMMMMMMMMMMMMMMJJJJFXXXXXLAAAAAAAAAAOOOOOOOOOOOYBBBBBBBBBBBBWZHHHPPPPPGGGGGGGGGGSSSSSTTTTQQQHHHHHHHHHHHHHHHH
        SIIILLUUUUUUUUUWWWWWGGQQQQQQQQQQQMMMMMMMMVVVVMJJJJJXXXXXXXYAAAAOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZZPPPPPPGGGGGGGGGGGSSSTTTTTTQQQHGGHHHHHHHHHHHH
        CCCCCCCUVVUUUUWWWWWQQQQQQQQQQQQQQQMMMMMMVVVZVVJJJJXXXXXXXXAAAAAOOOOOOOOOOOOOOYYZBBBBZBBBBBBBZZZPPPPPPGGGGGGGGGGGSSGRTTTTQQQQQGGGHHHHHHHHHHHH
        CCCCCCCCCCPKUUWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVJXXXXXXXXXNNAALOOOOOOOOOOOOOOYYYBBBBZBBBBBBBJZZOPPPPPPPGGGGGGGGGGGGGTTTTTTQQQQMMSSHHHHHHHHHH
        SSCCCCCCCCKKWWWWWWQQQQQQQQQQQQQQQMMMMVVVVVVVVVVXXXXXXXXXBBNNDALOOOOOOOOOOOOOOYYZBBBBBBBBBBBBZZZOPPPPPPUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKHKKKKKKK
        SCCCCCCCCKKWWWWWWWWQQQQQQQQQQQQQQQMMMMMVVVVVVVVQXXXXXXXXXBNNDAAOOOOOOOOOOOOOOYNNBBBBBBBBBBBBZOOOPPPPPUUUGGGGGGGGGGGGGTTTTTTQQZMMSSHKKKKKKKKK
        SCCCCCCCUKFWWWWWWWWWQQQQQQQQQQQQQEEMMMMVVVVVVVVVXXXXXXXXXXNNNAAOOOOOOXXXXXXXXYYNBBBBBBBBBBBZZOEEEEPPPUUUUGGGGGGGGGGGGGUUTZZZZMMMSMMMJJKKKKKK
        SSSCCCCCUGGGGWWWWWWWQQTQQQQQQEQQQEEMMMMMVVVVVVEEEXXXXXXXXNNNNNGOOOXXXXXXXXXXXQXNBBBBBBBBBBBZUUBEEEUUUUUUUUKGGGGGGTGGGGUUTZZZMMMMMMMMJJKKKKKK
        CCCICCCCGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMMVVVVVVEEEGXXXXXNXXNNIDGOOOXXXXXXXXXXXQQNBBBBBBBBBBBZUUUUUEUUUUUUUUUGGUGCCTTGUUUUUZZZPMMMMMMMJJKKKKKK
        CCCCCCCGGGGGGWWWWWWWWQQQQQQQQEEEEEEEEMMVVEVEVVEGEGGXRXNNDDDDDDGOOOXXXXXQQQQQQQQNNNBBBBBBBBBBBBUUUUUUUUUUUUUNCCCCCTCCCUUUUUUUUUUUUUUMMKKKKKKK
        HCCCCCCGGGGGGGGGWWWWWWWQQQQQQEEEEEEETTTTVEEEEEEGGGGXXMDDDDDDDDDGXXXXXXXXXQQQQQQQNNBBBBBBBBBBBBUUUUUUUUUUUUUUCCCCCCCCCCZUUUUUUUUUUUUMKKKKKKKK
        HCOCCCCGGGGGGGGGWWWWWKKKKQVVQEEETTTTTTTTTEEEEEEGGGGGVPXDDDDDDDDDDCCXXXXXXQHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUUCCCCCCACCCCZUUUUUUUUUUUUOKKKKKKKK
        CCCCCCCGGGGGGGGGGGWWIKKEEEVEBBEETTTTTTTTTEEGGGGGGGGGGPPPPPDDCCCCCCCXXXXXXHHQQQQQQVBBBBBBBBBBBBUUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUMMMMMOOOKKKKKKK
        CCJCWWWWGGGGGGGGGGWIIIKEEEEETBEETTTTTTTTTTTGGGGGGGGGEPBBBBDDBCCCCCCXXXXXXQHQQQZQQVBBBBBBBBBBBBUUUUUUUUUUUCCCCCCCCCCCCCKKKKUUUPPPPOOOOOKKKKKK
        GCCCCGGGGGGGGGGGGGIIIKKEEEEETTTTTTTTTTTTTTGGGGGGGGGGBBBBBBDDBBBCCCCCCRQQQHHHQQQQQVBBBBBBBBBBBBIUUUUUUUUUUUCCCCCCCCCCCCCKKKUUUPPPOOOLOYKKKQQK
        GGGGGGGGGGGGGGGGGGIIIIIEEEEETTTTTTTTTTTTTTGGGGGGGGGBBBBBBBBBBBCCCCCCCRRHHHHHQHHVVVBBBBBBBBIIIIIUUUUUUUUUUCCCCCCCCCCCCKKKKKPPPPPPPOOOYYYQQQQQ
        GGXGGGEGGGGGGGGGIIIIIIIEEEEEETTTTTTTTTTBDTGGGGGGGGGGGBBBBBBBBBCCCCCCCRRHHHHHHHHHVHHHHHIIIIIIIIMMMMUUUUUUCCCCCCCCCCCCCKKKKKKPPPPOOOOYYYYQQQQQ
        GXXGGGGGGGGGGGGGGIIIIIIEEEEETTTTTNTTTTTBDBBBGGGGGGGGGBBBBBBBBBBCCCCCCRLHHHHHHHHHHHHHHIIIIIIIIIIMUUUUUUIICCCCCCCCCCCCCKKKKKPPPPPOOPOYYYYYQQQQ
        XXXXGGGGGGGGGGGGGIIIIIIEEEEETTTTTNNETTBBBBBBGGGGGGGGGGBBBBBBBBBCCCCCCCHHHHHHHHHHHHHHIIIIIIIIIIIMMMMMUIIIICCCCCCCCCCCKKKPPPPPPPPOOPOYYYYYQQYY
        TXXGGGXCCGXGGGGGGIIIIIIEEEEEETTTTNNBBBBBBBBBBGGGGGGGGBBBBBBBBBBCCCCCCCCHHHHHHHHHHHHHIIIIIIIIIDHHMHHMUIIIICCCCIRRRRCCKKKKPPPPPPPPPPPYYYYYYYYY
        TXXXGGXXXXXGGGGGGFITTIIEEEEEEETTNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHHHHHIIIWWIHHMHHHHQHHIIIIIIIIRRRRKKKKNKPUPPPPPPPPPYYYYYYYYY
        XXXXXXXXXFXYFFGGFFFTTTTTEEEEEEENNNNBBBBBBBBBBBBGGGGGGBBBBBBBBBBBBCCCCCHHHHHHHHHHHHPIIIIIIIWIHHHHHHHHHHIIIIIIRRRRRRKKKNNIINPPPPPPPPYYYYYYYYYY
        XXXXXXXXJFFFFOOGGTTTTTTTTEEEEEEENNNBBBBBBBBBBBBGGGGGBBBBBBBBBBBBBCCCCCHHHHHHHHHHPHPIIIIIWWWBHHHHHHEEIRIIIIILLRRRRRKKKNNNNNPPPPPPYYYYYYYYYYYY
        GXXXXXKXXFFFFFOOOTTTTTTTTEEEEEENNNNBBBBBBBBBBBBBGGGTRRBBBBBBBBBBBCCCCCHHHHHHHHHHPPPIIIIIWWWHHHHHHHEEIIIIIZLLLLLLLLKKKNNNTTTJPPPOYYYYYYYYYRYY
        XXXXXXXXXFFOOOOXXTTTTTTTTEEEENNNNNNNBBBBBBBBBBBBBGGTRTTBBBBBBBBBHHCCHHTHHHHHHHHHPPIIIIIWWWWWHHHHHHHEEIIIILLLLLLLIIIIKINNNTTJPPPOYYYYYYYTYRRY
        XXXXXFXXXFXXXXOXTTTTTTTTTEEEENNNNNBBBBBBBBBBBBBBBBTTTTTBBBBBBBBMMHHHHHHHBHHHHPPPPPPPPIPPWWWWUHHHHHHEEEIILMLLLLLLLIIKKINNNTTTTTTTYYYYZTTTYRRY
        XXXXFFXXFFXXXXXXXXTTTTTTTEEEEMMMMBBBBBBBBBBBBBGGNNTTTTTTTTTBTBBBHHHHHHHHHHHHHPPPPPWPPPPWWWWWWWTHHHEEEIIELLLLLLLLIIIIIITTTTTTTTTYYYYTTTTTTRRR
        XXXOXFFXFXXQXXXXXXXTTTTTTEEMMMMMMMBBBBBBBGGGGGGGGGTTTTTTTTTTTNNHHHHHHHHHHHHHPPPPPPWWPWWWWWWWWWWEEEEEEEEELLLLLLLLLIIITTTTTTTTTTRYYYYQTTTTRRGR
        XXXXXFFFFFXXXXXXXTTTTTTTTTTTMMMMMMBBBBBBLLLGGGGHGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPPPCCCWWWWWWWWWWWWWEEEEEEELLLLLLLLLLILLOTTTTTTTTTTTYQQQQTTTQRRR
        XXXXFFFFFFXXXXXXTTTTTTTTTTTTTTMMMMBBMMLLLLLGGGGGGGTTTTTTTTTTTNNNHHHHHHHHHPPPPPCCCCCRWWWWWWWWWWEEEEEEEEELLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTTQQRQQ
        FFFFFFFFFFXXXXXXTTTTTTTTTTTXTTTMMMMMMMLLLLGGGGGGGGTTTTTTTTTTTTNVHHHHHHHHHHHPCCCCCCCCCWWWWWWWWEEEEEEEEEEVLLLLLLLLLLLLLTTTTTTTTTTTTQQQQTQQQQQQ
        FFFFFFFFXXXXXXXXTTTTTTTTTXXXTSTXXMMMMLLLLLLLGGLTTTTTTTTTTTTTTVVVHHHHHHHHHHHCCCCCCCCCWWWWWWWWWWWWEEEEVVVVVVLVVLLVVVBBWWTTTTTTTTTTTTQQQQQXQXXQ
        FFFFFFFFFXXXXXXXXTTTTTTTTTXXXXXXXXMMMMMLLLLLLOLDDDDDTTTTTTTQQQQQHWHHHHHHHCCCCCCCCCCCCWWWWWWWWWWWEWWEVVVVVVVVVVLVVVBBBWTTTTTTTTTTTTQQQQQXXXXX
        FFFFFFFFFFXXXXXXJJTTTTTTTMXXXXXXXXXMIIMLLLLLLLLDDDDTTTTTTQQQQQQHHHHHHHHHHCCCQCCCCCCCWWWWWWWWWWWLWWWVVVVVVVVVVVVVVVPBBWTTTTTTTTTTTTQQQQQQQXXX
        FFFFFFFFFFFXXXXJJTTTTTTTTMMXXXXXXXIIIILLLPLLDRDDDDDTTTTQTQQQQQEHHHHHHHHHHHHCCCCCCCZCWWWWWWWWWWWWWWWVVVVVVVVVVVVVVBBBBWTTTTTTTTTTTTQQQQQQQQXX
        FFFFFFOFFFOIXIJJJJJJJJJJJXXXXXXXXXIIIIIELPLLDDDDDDDDTTQQQQQQQQEEHEEHHHHHHRRRRRCCCCZCEEWWWWWWWWWWWWWVVVVVVVVVVVVVVVBBBBTTTTTTTTTTTQQHHHQQQQXQ
        FFFFOOOOOOOIIIIJJJJJJJJJJXXXXXXXUIIIIIIELILLDDDDDDDDTTQQQQQQQQEEEEHHHHVVVVVRRRCCJJJJJJWJJWWWWSDDWWWVVVVVVVVVVVVVBBBBBBBBTBBBBTTRTHHHHHHHHQXQ
        FFFFFFFOOOIIIIIJJJJJJJJJXXXXIXXUUIIIIIIIIIIIEDDDDDDDQTQQQQQQQQEEVVVVVVVVVVVRRRCCJJJJJJMEEWWWSSSDSSWVVVVVVVVVVVVBBKBBBBBBBBBBBTTRRHHHHHHHQQQQ
        FFFFFFOOOIIIIIYZJJJJJJJJIEIXIXUUUUIIIIIIIIIEEEEDDDDAQQQQQQQEEEEOVVVVVVVVVVVRRRCCJJJJJJJETTTTSVSDSSSVVVVVVVVVVVVBBBBBBBBBBBBBRRRRHHHHHHQHQQQQ
        FFFFFFFOOOIYYYYJJJJJJJJIIIIIIUUUUUIIIIIIIIIEEEDDDDAAAQQQQQQEEEOKVVVVVVVVVVVRRRRRJJJJJJJEEETTSSSSSSSVVVVVVVVVVBBBBBBBBBBBBBBRRRRDHHHHHHQQQQQQ
        FFFFFFFOOOOOYYYYYYYYJJIIIIIIIUUUUPIIIIIIIIIEEEDEDDDAAQQQQQQOEOOOOOOLXXVVVVVRRRRJJJJJJJOEEEEESSSSSSSSSVVVVVVVVBBBBBBBBFBFBBBBBDDDDDHHQQQQQQQQ
        FHHFFOOOOOOOOYYYYYJJJJIIIIIIPUUUPPPPIIIIIIQQQEEEEDAAAAAQXQOOOOOOOOOOXXVVVVVRRRRJJJJJJJJEEEESSSSSSSSSVVVVVVVVJBJJBBBBBFFFBBBTTTDDDDHHQQQQQQQQ
        HHHHFOOOOOOJOYYYYYJJJJIIIIIPPPUPPPPPIIIIIQQPPQQAAAAAAAXXXXOOOOOOOOOOXXVVVVVRJJJJJJJJJJJEEEESSSSSSSSVVVVVVJJJJJJJBBBBFFFFFBBTDDDDDDHHHQQQQQQQ
        HHOOOOOOOOOOOYYYYYJJJJIIIIIIPPPPPPPPQQQQQQQQQQQAAAAAAAXXXXOOOOOOPOOOOXXXXXXRRJJRJJJEEEEEEEEEEESSSSSSVVVVVJJJJJJJJBBBFFFFFFBTDDDDDDDMQQQQQQQQ
        HHHOOOOOOOOJJJJYJJJJJGGGIIIIPPPPPBPQQQQQNQQQQQQQQAAAAAAXXXOOOOOOOOOXXXXXXXRRRRRRJJJJEEEEEEEEEEESSSSSSVVVVDJAJJJJJJFFFFFFFFSDDDDDDDDQQQQQQQQQ
        HHHHOOOOOOOJJJJJJJJJJGGGGGIPPPPPPBBQQQQQNNNNQQQQQAAAAAAAAXOOOOOOOOOXXXXXXXRRRRRRRRJEEEEEEEEEEEEEESSSSSVVSSAAJJJJJJFFFFFFFFDDDDDDDDDQQQQQQQQQ
        HHHHHOOOOJJJBBBBBJJJGGGGGIIIPPPPPBBQQQQQNNNDQQLAAAAAAAAAXXXOOOOOOOXXXXXXJXRRRRRRREJEEEEEEEEEGEEEESSSSSSSSSSSBJJJJJJSFFFFFFFFDDDDDDDQQQQQQQQQ
        HHHHHHHHHHJJBBBBBBBGGGGGGGIIIIPPPBBBQQQQNDNDQQLLAAGAKKKKXXXXXONOOOXXXXXXJXXRRRRRREEEEEEEEEEELEKEELSSSSSSSSSYJJJJJJJSFFFFFFLDDDDDDQQQQQQQQQQQ
        HHHHHHHHBJJJBBBBBBBGGGGGEIIIIIPPPPBQQQQQDDNDLLLLLGGGGKKKXXXXXKNNOOXXXXXXJXRRRRRRRUEEEEEEEEELLLLEILLLLSSSSSSYJJJJJJJYFJJJFJJJDDDDDDQQQQQQQQQQ
        HHHHHHHHBBBBBBBBBBBGGGGGGGGIIPPPPPPDDQQQDDDDLLLLLGGGGKKKKKXXXKNOOOJJJXJJJRRRRRRRREEEEEEEEELLLLLLLLLLLSSSSSSJJJJJJJJYYJJJJJJWDDDDDDQQQYYYQQQQ
        HHHHHHHBBBBBBBBBBBBBGGGGGGGBBBBBPPDDDDDDDDDDLLLZLLGGGKKKKKKKKKNNNOJJJJJJJRRRRRRDDDDDEEEEEELLLLLLLLLLLLLSSSJJJJJJJJJYYYJJJJJJDDDKQQQQYYYYYQQQ
        HHHHHHBBBBBBBBBBBBBBGGGGGGGGBBBBMMDDDDDDDDDDLLLLLGGGGKKKKKKKKKNJJJJJJJJJJJRRRRRDDDDDDDELLELLLLLLLLLLLLLLLSCCAJJJJJYYYJJJJJJJJJDGQQGGYYYYYQQQ
        HHHHHHHHBBBBBBBBBBBBGGGGGGGGGBBMMDDDDDDDDDDLLLLLLGKKGKKKKKKKKKNJJJJJJJJJJJJRRRDDDDDDDEELLLLLLLLLLLLLLLLLASACAAAYJYYYYYYJXJJJJKGGGGGGGAYYQQQQ
        HHHHHHHBBBBBBBBBBGGGGGGGGGGBBBBMMMDDDDDDDDDDLLRLXXKKKKKKKKKKKKNNUUJJJJJJJJJRRRRDDDDDDELLLLLLLLLLLLLLLLLAAAACAAAYJYYYYYYJXXEEJGGGRRRRAAYYIQQQ
        HHHHHHBBBBBBBBBBBGGGGGGQQQGQBQQMMMDDDDILLLDLLLLLXXXKKKKKKKKKKNNNNUUJJUUJJJJJRJJJDDDDLLLAAAAALLLLLLLLLLIAAAAAAAAYYYYYYYXXXXXEEEGGRRRRGAYQQQQA
        HHHHHHBBBBBBBBBBBBGHGGGQQQQQQQQMMMIIIIILHLLLLLQQXXXXXKKKKKKKKKNNNUUUUUUJJJJJJJJJJJDAAAAAAAAAALLLLLLLLAIAAAAAAAAAYYYYYXXXXXXGGGGGRRRRGAAAAAAA
        HHHHHHHBBBIBBBBBBHHHGQQQQQQQQQQMIIIIIIIIIILLDDXQXXXXXXJJKKKKKKNNNNUUUUUUUUJJJJJJJAAAAAAAAAAAALLLLLLLLAAAAAAAAAAYYYYYYYYYYXXGGGGGRRRRGAAAAAAA
        HHHHHHHHHIIIBBHBBHHHQQQQQQQQQQQMMIIIIIIIIIILIIXXXXXXXJJJKJJKKKNNNUUUUUUUUJJJJJJJJJGGAAAAAAAAALLLLLLLAAAAAAAAAAAAYYYYYYYYYYYYGGGGRRRRAAAAAAAA
        HHHHHLLHHHHHBBHHHHHQQQQQQQQQQQQQIIIIIIIIIIIIIICCCCCCCCCJJJJJJUUUUUUUUUUUDUJJJJJJJGGAAAAAAAAAALLLLLLZOOAAAAAAAAAAAYYYYYYYYYGGGGGGRRRRGAAAAAAA
        HLHHLLLLHHHHHHHHHHHHFQQQQQQQQQQQQIIIIIIIIIIIIICCCCCCCCCJJJJJJOOUUUUUUUUUUUJJJJJJJJAAAAAAAAAAALDDVVLZOOOAAAAAAAAAAYYYYYYYYYYYGGVGRRRRPAAAAAAA
        HLLHLLLDHHHLHHHHHHHHQQQQQQQQQQQQQIIIIIIIIIIIHICCCCCCCCCJJJJJJJJJJUUUUUUUUUJJJJJJJJIIIAAAAAAAAXDDVVVOOOOAAAAAAAAAAAAYYYYYYYYYKKGGRRRRPAAAAAAA
        HHLLLLLLLLHLLHHHHHHHXQQQQQQQQQQQUUIIIIIIIIIIHICCCCCCCCCCCCCJJJJJJUUUUUUUUUJJJJJJJJJIIAAAAXYXXXXXVVVVOAAAAAAAAAAAAAAYYYYYYCCCKKGGRRRRPPPPZZZA
        LLLLLLLLLLLLLHYHHHHHXQQQQQQQQQQQUIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUUUMPJSJIIIIIIACXXXXXXXXVVVVAAAAAAAAAAAAAAYYYYYYYCCCKKRRRRRRPPPPMZZZ
        LLLLLLLLLLLLLLYYYYYYXXXXQQQQQQQIIIIIIIIIIIIIIICCCCCCCCCCCCCJJJJJJUUUUUUUUMMMMSSSISIIIICCCXXXXXXXXVVVVVVVAAAAAAAALLYYYYYCCCCCCCPPPPPPPPPPZZBZ
        LLLLLLLLLLLLVYYYYYYYXXXXXQQQQQQIIIIICCIIIIIIIICCCCCCCCCCCCCCCJJJJUUUUUMMMMMMMMSSSSSSSICXXXXXXXXXXXXXVVVVAAVAAALLLLYYYYYCCCCCCCCCPZPPPPPPZZZZ
        LLLLLLLLLLLLVYYYYYYXXXXXQQQQQQIIIIIIIIIIIIIIMIGGGGGGGUCCCCCCCJJJJJUUUUMMMMMMMSSSSSSSSSSUXXXXXXXXXXXVVVVVAAVAVAALVCYYYYCCCCCCCCCCPPPPPPPPPPOO
        LLLLLLLLLLLLYYYYYYXXXXXXQQQYIQIIIIIIIIIIIIIIMGGGGGGGGGCCCCCCCJJJJJJJUUMMMMMMSSSSSSSSSSSSXXXXXXXXXXXVVVVVVVVVVVVVVCYYYYCCCCCCCCCCPPPPPPPPPOOO
        LLLLLLLLLLLLYYYYYYXXXXXXXQXIIIIIIIIIIUIIIIIIMGGGGGGGAACCCCCCCJJJCJUUUUMMMMMMSSSSSSUSSSSFXXXXXXXXXXXVVVVVVVVVVVVGVCGGGEEECCCCCCCCCPPPPPPPPOOO
        LLLKLLLLLLLYYYYYYYXXXXXXXQIIIIIIIIIIIUUIIIMMMGGGGGGAAWWWWJJJJJJCCJUUUUMMMMMMSSKKKSUSSSSXXXXXXXXXXXXXVVVVVVVVVVVGCCGGEEEEFCCCCCCCCPPPPPPPPOOO
        LLKKLLYLLLYYYYYYYYLLXXXXXXXXIIIIIIIIIUMMMIIMMMGGMMGAAAWWWJJJJJJJCCCMMMMMMMMMMMKKKKWWWZZXXXXXXXXXXXXVVVVVVVVVXGVGGGGEEEEEFCCCCCCCCPPPPPPPPOOO
        LKKKKYYYYYYYYYYYYYSLXXLXLLIIIIIIIIIIIUMMMMMMMMMMMGGAAWWWWJJJJJJCCCCCCMMMMMMMMKKWKWSWWZZXZZXXXXXXMMXVVVVVVVVXXGGGGEGEEEEEFCCFCCCCCPPPPYYROOOO
        LKKKKKYYYYYYYYYYYYYLXXLXLLIIIIIIIIYYYYMMMMMMMMMMMWWAAAWWWWJJJJCCCCCCMMMMMKKKKKKWWWWWWZZZZZXXXXXXMVVVVVVVVVVXXGXEEEEEEEEEFFFFCCFPPPPPPRRRRROO
        KKKKKKKYYYYYYYYYYLYLLLLLLLLIIIIMIIIYYYMMMMMMMMMMMWWWWWWWWWCJJCCCCCCCMMMMKKKKKKWWWWWWWZZZZZXXRXXRMVVVVVXXXXXXXGXXEETEEEEFFFFFFFFPPPPPPPRRRROR
        KKKKKKYYYYYYYYYYYLLLLLLLLLIIIMMMMIMMYYYMMMMMMMMMMMWWWWWWWWCCCCCCCCCCMMDKKKKKKKWWWWWWWWZZZZXXRRRRRRRVVVVVLXXXXXXXXETFFFFFFFFFFFFFPPPPPRRRRRRR
        KKKKKKYYYYYYYYYYYLLLLLLLLLMMMMMMMMMYYYYYMMMMSSMSMSWWWWWWWCCCCCCCCCCCMMDCFCKKKWWWWWWWWWZWWZZRRRRRRRRVVVXXXXXXXXXXXXXXFFFFFFFFFFFPPPPPPRRRRRRR
        KKKKKKKYYYYYYYYYLLLLLLLLLLLLLMMMMMMMMYYSSSSSSSSSSSWWWWWWWCCCCCCCCCCCCCCCFCKKKKWWWWWWWWWWZZZZRRRRRRRVVVHXXXXXXXXXXXXXXFFFFFFFFFFFPPFIIIRRRRRR
        KKKKKKKKYYYYYYYYKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSWWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKWRRRRRRRHRRRRVHHXXXXXXXXXXXXFFFFFFFFFFFFFFFFIIIRRRRRR
        KKKKKKKKKKYYKYYKKKLLLLLLLLLLMMMMMMMMMSSSSSSSSSSSSSWWWWWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWWKKRCRRRRHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIRRDR
        KKKKKKKKKKKKKKKKKKLLLLLLLLLLLMMMMMMMMSSSSSSSSSSSSSRRRRWWWWCCCCCCCCCCCCCCCKKKKKKWWWWWWKKKKRRRRRHHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFIIIIIIIIRDD
        KKKKKKKKKKKKKKKKKKLLLLLLLLLLMMMMMMMMMRSSSSSSSSSSSSRRRRRRRVVCCVVVVVCCCCCCCKKKKKKKKWWKKKKKKKRRRRHHHHHHHHXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIIIDD
        KKKKKKKKKKKKKKKKKKLKLLLLLLLMMMMMMMMMMMKSSSSSSSSSSSSSRRRRVVVVVVCCCCCCCCCCCKKKKKKKKKWKKKKKKKRRRRRHHHHHHHXXXXXXXXXXXXXFFFFFFFFFFFFFFFIIIIIIIDDD
        KKKKKKKKKKKKKKKKKKKKKKKLMMMMMMMMMMMMMMKSSSSSSSSSSSSRRRRRRRRVCCCCCCCCHHCCCKKKKKKKKKKKKKKKRRRRHHHHHHHHHHXXXXXXXXXXXXXXFFFFFFFFFFFFFIIIIIIIIDDD

        """;
}
